# Generated by Django 5.2.16 on 2026-07-21 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('channel', models.CharField(choices=[('Email', 'Email'), ('Phone', 'Phone'), ('SMS', 'SMS'), ('WhatsApp', 'WhatsApp'), ('Chat', 'Chat')], max_length=20)),
                ('direction', models.CharField(choices=[('Inbound', 'Inbound'), ('Outbound', 'Outbound')], max_length=20)),
                ('summary', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
